### ISSUE TITLE
NullPointerException at org.mobilitydata.gtfsvalidator.validator.ParentLocationTypeValidator.validate(ParentLocationTypeValidator.java:64)

### ISSUE THREAD

**Issue by markstos** [MobilityData/gtfs-validator#1010]
## **Bug report** 

```
SEVERE: Runtime exception when loading stops.txt
java.lang.NullPointerException
	at org.mobilitydata.gtfsvalidator.validator.ParentLocationTypeValidator.validate(ParentLocationTypeValidator.java:64)
	at org.mobilitydata.gtfsvalidator.validator.ValidatorLoader.invokeSingleFileValidators(ValidatorLoader.java:205)
	at org.mobilitydata.gtfsvalidator.table.GtfsStopTableLoader.load(GtfsStopTableLoader.java:152)
	at org.mobilitydata.gtfsvalidator.table.GtfsFeedLoader.lambda$loadAndValidate$0(GtfsFeedLoader.java:113)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

This happens in a private GTFS feed that I can't provide but based on the file name involved, it looks there was a mismatch between the stop ID and the parent ID. This particular feed provider in the past has had a problem using the same ID for stops and the parent station.

**Expected behaviour**

Validator should report validation problems instead of crashing.

**Observed behaviour**

Crasher.

**Environment versions**
- validator version: 2.0.0 
- Java version: openjdk 11.0.12
- OS versions: Arch Linux

**Comment by lionel-nj** [comment]
Thanks @markstos for flagging that and opening the issue. Work has started in https://github.com/MobilityData/gtfs-validator/pull/1011 to fix this bug.

**Comment by markstos** [comment]
I've confirmed this issue is fixed in the latest snapshot. I see foreign key validations in the error report, which is perfect.

**Comment by markstos** [comment]
Thanks for helping Netflix with their transit!

**Comment by isabelle-dr** [comment]
No problem!

**Comment by aababilov** [comment]
My pleasure!
