### ISSUE TITLE
bug: Version number fails to resolve on Windows app

### ISSUE THREAD

**Issue by bdferris-v2** [MobilityData/gtfs-validator#1181]
When running the Windows packaged application, the version number of the app fails to resolve.

**How we reproduce the bug**

1. Install the packaged GTFS Validator app on Windows.
2. Run validation on a feed.
3. Observe that version info is missing in the output report and in logs.

**Expected behaviour**
Version info should be present in the report.

**Observed behaviour**
Current version is missing.

**Screenshots:** 

![Screen Shot 2022-06-03 at 9 05 24 PM](https://user-images.githubusercontent.com/26211219/171982105-676f8d3d-388f-4271-8249-01ba20697550.png)

Logs:
```
Jun 03, 2022 4:36:29 PM org.mobilitydata.gtfsvalidator.runner.ValidationRunner run
INFO: VersionInfo: Version

Info{currentVersion=Optional.empty, latestReleaseVersion=Optional.empty}
```

**Environment versions**
- validator version: 3.1.0
- Java version: embedded
- OS versions: Windows 10

**Comment by bdferris-v2** [comment]
This does not repro for the 3.1.0 CLI jar on Windows or Mac OS.  I've verified that the version number is correct in the jar's `META-INF/MANIFEST.MF` file.

**Comment by bdferris-v2** [comment]
It also doesn't repro when running the app locally via `./gradlew app:gui:run` but does repro when running the packaged app on both Windows and Mac OS.  I've discovered that there's an exception being thrown within the `VersionResolver` background executor thread:

```
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
        at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
        at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
        at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
        at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Unknown Source)
        at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
        at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
...
```

It unfortunately not caught by the uncaught exception handler because it's on a new thread.

If I had to guess, I'm thinking this must be a Java Module permissions issue?

**Comment by bdferris-v2** [comment]
Adding module dependencies on `jdk.crypto.ec` and `jdk.crypto.cryptoki` seems to fix the issue.

For the record, this issue also means that the validator will fail to download feeds from a url that uses https.

Per https://stackoverflow.com/questions/55439599/sslhandshakeexception-with-jlink-created-runtime
