### ISSUE TITLE
Last commit failed to create Windows runtime

### ISSUE THREAD

**Issue by fredericsimard** [MobilityData/gtfs-validator#1338]
### Describe the bug

The action reported an error when trying to package the Windows app of the validator.

https://github.com/MobilityData/gtfs-validator/actions/runs/4175763001/jobs/7231223420

### Steps/Code to Reproduce

Don't know how it happened, I received an email warning me of that error. Seems to be timed with this commit: https://github.com/MobilityData/gtfs-validator/pull/1336

```
Error: Exception in thread "main" java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:484)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:478)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1507)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1417)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:572)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:201)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:[25](https://github.com/MobilityData/gtfs-validator/actions/runs/4175763001/jobs/7231223420#step:5:26)0)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:100)
	at org.gradle.wrapper.Download.download(Download.java:80)
	at org.gradle.wrapper.Install$1.call(Install.java:68)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
Error: Gradle build failed: see console output for details
```

### Expected Results

That the app gets package correctly.

### Actual Results

No app was packaged.

### Validator version

Latest

### Operating system

Windows

**Comment by bdferris-v2** [comment]
I think this is an intermittent failure.  The workflow completed successfully when I requested a rerun and this workflow has completed successfully for other PRs in the meantime.

**Comment by fredericsimard** [comment]
Awesome! I'll know for next time. Tx!
