### ISSUE TITLE
Runtime exception in validator: java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by qcdyx** [MobilityData/gtfs-validator#1538]
### Describe the bug

Jul. 11, 2023 4:31:20 P.M. org.mobilitydata.gtfsvalidator.table.GtfsFeedLoader loadAndValidate
INFO: Loading in 1 threads
Jul. 11, 2023 4:31:20 P.M. org.mobilitydata.gtfsvalidator.validator.ValidatorUtil safeValidate
SEVERE: Runtime exception in validator org.mobilitydata.gtfsvalidator.validator.AgencyConsistencyValidator
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at org.mobilitydata.gtfsvalidator.validator.AgencyConsistencyValidator.validate(AgencyConsistencyValidator.java:83)
	at org.mobilitydata.gtfsvalidator.validator.ValidatorUtil.safeValidate(ValidatorUtil.java:74)
	at org.mobilitydata.gtfsvalidator.validator.ValidatorUtil.invokeSingleFileValidators(ValidatorUtil.java:55)
	at org.mobilitydata.gtfsvalidator.table.AnyTableLoader.loadMissingFile(AnyTableLoader.java:196)
	at org.mobilitydata.gtfsvalidator.table.GtfsFeedLoader.loadAndValidate(GtfsFeedLoader.java:131)
	at org.mobilitydata.gtfsvalidator.runner.ValidationRunner.loadAndValidate(ValidationRunner.java:204)
	at org.mobilitydata.gtfsvalidator.runner.ValidationRunner.run(ValidationRunner.java:122)
	at org.mobilitydata.gtfsvalidator.cli.Main.main(Main.java:68)

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

### Steps/Code to Reproduce

- Run the following command:
java -Xmx1G -jar ./cli/build/libs/gtfs-validator-4.1.1-SNAPSHOT-cli.jar -o ~/code/data/gtfs-ws/delfi -i /Users/jingsi/Downloads/winzip.zip

### Expected Results

No java.lang.IndexOutOfBoundsException

### Actual Results

SEVERE: Runtime exception in validator org.mobilitydata.gtfsvalidator.validator.AgencyConsistencyValidator
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0

### Validator version

v4.1.1

### Operating system

MacOS

**Comment by qcdyx** [comment]
This issue only occurs when agency.txt is missing.
