### ISSUE TITLE
[BUG] Validator crashes on color luminance check

### ISSUE THREAD

**Issue by nickaein** [MobilityData/gtfs-validator#288]
**Describe the bug**
The validator crashes at the beginning of validation process.

**To Reproduce**
-

**Expected behavior**
The validator should not crash.

**Witnessed behavior**
The validator crashes.

Here is the command arguments, log output and stacktrace which might be useful

```
$ java -jar gtfs-validator-v1.2.0.jar -i Archive.zip -o gtfs_out -e gtfs_extract
[WARN ] 2020-06-19 23:15:37.112 [main] Main - Configuration file execution-parameters.json not found in working directory

[INFO ] 2020-06-19 23:15:37.254 [main] Main - Retrieving execution parameters from command-line

[INFO ] 2020-06-19 23:15:37.264 [main] Main - Unzipping archive

[INFO ] 2020-06-19 23:15:37.436 [main] Main - No file to exclude -- will execute validation process on all files

[INFO ] 2020-06-19 23:15:37.442 [main] Main - List of filenames to exclude is: []

[INFO ] 2020-06-19 23:15:37.443 [main] Main - Will execute validation on the following subset of files: [agency.txt, stops.txt, routes.txt, trips.txt, stop_times.txt, fare_attributes.txt, calendar.txt, fare_rules.txt, shapes.txt]

[INFO ] 2020-06-19 23:15:46.281 [main] Main - Validating rule 'W005 - Route short name too long'

[INFO ] 2020-06-19 23:15:46.284 [main] Main - Validating rule 'E025 - Insufficient route color contrast'

Exception in thread "main" java.lang.StringIndexOutOfBoundsException: begin 0, end 2, length 1
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
        at java.base/java.lang.String.substring(String.java:1874)
        at org.mobilitydata.gtfsvalidator.usecase.ValidateRouteColorAndTextContrast.luminance(ValidateRouteColorAndTextContrast.java:66)
        at org.mobilitydata.gtfsvalidator.usecase.ValidateRouteColorAndTextContrast.contrast(ValidateRouteColorAndTextContrast.java:82)
        at org.mobilitydata.gtfsvalidator.usecase.ValidateRouteColorAndTextContrast.areContrasting(ValidateRouteColorAndTextContrast.java:100)
        at org.mobilitydata.gtfsvalidator.usecase.ValidateRouteColorAndTextContrast.lambda$execute$0(ValidateRouteColorAndTextContrast.java:56)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
        at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1675)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at org.mobilitydata.gtfsvalidator.usecase.ValidateRouteColorAndTextContrast.execute(ValidateRouteColorAndTextContrast.java:57)
        at org.mobilitydata.gtfsvalidator.Main.main(Main.java:140)
```

**Environment used**
- OS: Ubuntu 20.04 LTS
- Java version: openjdk 11.0.7 2020-04-14
- gtfs-validator version: v1.2.0
 
**Additional context**

**Comment by lionel-nj** [comment]
Hello @nickaein  thanks for your contribution, our MobilityData team will soon analyze and work on it.

**Comment by barbeau** [comment]
@nickaein could you share the GTFS you were validating?

**Comment by nickaein** [comment]
Thank you for the prompt response!

Sadly I can't provide it, based on our company policy. I will try soon to see if a minimal GTFS can be prepared that can reproduce the issue.

**Comment by nickaein** [comment]
Found the bug! The issue is that in our `routes.txt` file there are some rows with an invalid value for `route_color` or `route_text_color` (e.g. `E+47`, `0`). It would be nice to add a validation rule to make sure the given color is indeed [an six-digit hex string as stated](https://gtfs.org/reference/static#field-types).

BTW, thanks for the awesome library! It even checks color contrast which is pretty cool.

**Comment by barbeau** [comment]
@nickaein Thanks for the info! The validator should be catching those invalid values without crashing, so I'll leave this issue open so the parsing code can be updated. If you can provide examples of other invalid values in file that would be great.

**Comment by nickaein** [comment]
Sure! Those two (`E+47` and `0`) were the only cases in our data that cause the crash.

**Comment by maximearmstrong** [comment]
@nickaein Could you share a single line containing these invalid values?

**Comment by fabrice-v** [comment]
@nickaein It's our pleasure to let you know that [release v1.2.1](https://github.com/MobilityData/gtfs-validator/releases/tag/v1.2.1) contains the fix regarding this issue.

Thks again for your contribution!
