### ISSUE TITLE
[BUG] Memory error in processing MBTA Feed

### ISSUE THREAD

**Issue by e-lo** [MobilityData/gtfs-validator#383]
**Describe the bug**
Memory error when processing MBTA Feed.  

**To Reproduce**
`java -jar gtfs-validator-v1.2.2.jar -u https://transitfeeds.com/p/mbta/64/20200531/download -i input.zip -e input -o output -abort_on_error false`

**Expected behavior**
Validation w/out error.

**Witnessed behavior**
Error: `Exception in thread "main" java.lang.OutOfMemoryError: Java heap space`

**Environment used**
- Hardware: MacBookPro w/ 16 GB 2133 MHz LPDDR3 Memory
- OS: [openjdk:16-slim](https://www.google.com/search?q=openjdk%3A16-slim&oq=openjdk%3A16-slim&aqs=chrome..69i57j69i58j69i61.775j0j7&sourceid=chrome&ie=UTF-8) - *note that I am running this in Docker, but without a memory cap*
- Java version: 
```sh
java --version
openjdk 16-ea 2021-03-16
OpenJDK Runtime Environment (build 16-ea+16-712)
OpenJDK 64-Bit Server VM (build 16-ea+16-712, mixed mode, sharing)
```
- gtfs-validator version:  1.2.2

**Additional context**
Traceback:

```sh

java -jar gtfs-validator-v1.2.2.jar -u https://transitfeeds.com/p/mbta/64/20200531/download -i input.zip -e input -o output -abort_on_error false
[WARN ] 2020-09-21 22:24:42.635 [main] Main - Configuration file execution-parameters.json not found in working directory
[INFO ] 2020-09-21 22:24:42.643 [main] Main - Retrieving execution parameters from command-line
[INFO ] 2020-09-21 22:24:43.131 [main] Main - Downloading archive
[INFO ] 2020-09-21 22:24:50.206 [main] Main - Unzipping archive
[INFO ] 2020-09-21 22:24:50.691 [main] Main - No file to exclude -- will execute validation process on all files
[INFO ] 2020-09-21 22:24:50.699 [main] Main - List of filenames to exclude is: []
[INFO ] 2020-09-21 22:24:50.699 [main] Main - Will execute validation on the following subset of files: [agency.txt, stops.txt, routes.txt, trips.txt, stop_times.txt, levels.txt, transfers.txt, calendar.txt, pathways.txt, calendar_dates.txt, shapes.txt, feed_info.txt]
[INFO ] 2020-09-21 22:24:50.726 [main] Main - Validate CSV structure and field types for file: agency.txt
[INFO ] 2020-09-21 22:24:50.728 [main] Main - Validating rule 'E_039 & W_009 - Empty file'

[INFO ] 2020-09-21 22:24:50.788 [main] Main - Validating rules :'E001 - Missing required field
[INFO ] 2020-09-21 22:24:50.788 [main] Main -                   'E043 - Duplicated field
[INFO ] 2020-09-21 22:24:50.788 [main] Main -                   'W002 - Non standard field name
[INFO ] 2020-09-21 22:24:50.889 [main] Main - Validate CSV structure and field types for file: stops.txt
[INFO ] 2020-09-21 22:24:50.889 [main] Main - Validating rule 'E_039 & W_009 - Empty file'

[INFO ] 2020-09-21 22:24:50.893 [main] Main - Validating rules :'E001 - Missing required field
[INFO ] 2020-09-21 22:24:50.893 [main] Main -                   'E043 - Duplicated field
[INFO ] 2020-09-21 22:24:50.894 [main] Main -                   'W002 - Non standard field name
[INFO ] 2020-09-21 22:24:52.041 [main] Main - Validate CSV structure and field types for file: routes.txt
[INFO ] 2020-09-21 22:24:52.043 [main] Main - Validating rule 'E_039 & W_009 - Empty file'

[INFO ] 2020-09-21 22:24:52.055 [main] Main - Validating rules :'E001 - Missing required field
[INFO ] 2020-09-21 22:24:52.056 [main] Main -                   'E043 - Duplicated field
[INFO ] 2020-09-21 22:24:52.059 [main] Main -                   'W002 - Non standard field name
[INFO ] 2020-09-21 22:24:52.123 [main] Main - Validate CSV structure and field types for file: trips.txt
[INFO ] 2020-09-21 22:24:52.127 [main] Main - Validating rule 'E_039 & W_009 - Empty file'

[INFO ] 2020-09-21 22:24:52.137 [main] Main - Validating rules :'E001 - Missing required field
[INFO ] 2020-09-21 22:24:52.138 [main] Main -                   'E043 - Duplicated field
[INFO ] 2020-09-21 22:24:52.141 [main] Main -                   'W002 - Non standard field name
[INFO ] 2020-09-21 22:24:54.476 [main] Main - Validate CSV structure and field types for file: stop_times.txt
[INFO ] 2020-09-21 22:24:54.477 [main] Main - Validating rule 'E_039 & W_009 - Empty file'

[INFO ] 2020-09-21 22:24:54.479 [main] Main - Validating rules :'E001 - Missing required field
[INFO ] 2020-09-21 22:24:54.479 [main] Main -                   'E043 - Duplicated field
[INFO ] 2020-09-21 22:24:54.479 [main] Main -                   'W002 - Non standard field name
[INFO ] 2020-09-21 22:25:40.919 [main] Main - Validate CSV structure and field types for file: levels.txt
[INFO ] 2020-09-21 22:25:40.921 [main] Main - Validating rule 'E_039 & W_009 - Empty file'

[INFO ] 2020-09-21 22:25:40.924 [main] Main - Validating rules :'E001 - Missing required field
[INFO ] 2020-09-21 22:25:40.924 [main] Main -                   'E043 - Duplicated field
[INFO ] 2020-09-21 22:25:40.924 [main] Main -                   'W002 - Non standard field name
[INFO ] 2020-09-21 22:25:40.941 [main] Main - Validate CSV structure and field types for file: transfers.txt
[INFO ] 2020-09-21 22:25:40.941 [main] Main - Validating rule 'E_039 & W_009 - Empty file'

[INFO ] 2020-09-21 22:25:40.945 [main] Main - Validating rules :'E001 - Missing required field
[INFO ] 2020-09-21 22:25:40.945 [main] Main -                   'E043 - Duplicated field
[INFO ] 2020-09-21 22:25:40.946 [main] Main -                   'W002 - Non standard field name
[INFO ] 2020-09-21 22:25:41.007 [main] Main - Validate CSV structure and field types for file: calendar.txt
[INFO ] 2020-09-21 22:25:41.008 [main] Main - Validating rule 'E_039 & W_009 - Empty file'

[INFO ] 2020-09-21 22:25:41.017 [main] Main - Validating rules :'E001 - Missing required field
[INFO ] 2020-09-21 22:25:41.017 [main] Main -                   'E043 - Duplicated field
[INFO ] 2020-09-21 22:25:41.019 [main] Main -                   'W002 - Non standard field name
[INFO ] 2020-09-21 22:25:41.240 [main] Main - Validate CSV structure and field types for file: pathways.txt
[INFO ] 2020-09-21 22:25:41.240 [main] Main - Validating rule 'E_039 & W_009 - Empty file'

[INFO ] 2020-09-21 22:25:41.256 [main] Main - Validating rules :'E001 - Missing required field
[INFO ] 2020-09-21 22:25:41.256 [main] Main -                   'E043 - Duplicated field
[INFO ] 2020-09-21 22:25:41.259 [main] Main -                   'W002 - Non standard field name
[INFO ] 2020-09-21 22:25:42.299 [main] Main - Validate CSV structure and field types for file: calendar_dates.txt
[INFO ] 2020-09-21 22:25:42.300 [main] Main - Validating rule 'E_039 & W_009 - Empty file'

[INFO ] 2020-09-21 22:25:42.303 [main] Main - Validating rules :'E001 - Missing required field
[INFO ] 2020-09-21 22:25:42.303 [main] Main -                   'E043 - Duplicated field
[INFO ] 2020-09-21 22:25:42.304 [main] Main -                   'W002 - Non standard field name
[INFO ] 2020-09-21 22:25:42.324 [main] Main - Validate CSV structure and field types for file: shapes.txt
[INFO ] 2020-09-21 22:25:42.324 [main] Main - Validating rule 'E_039 & W_009 - Empty file'

[INFO ] 2020-09-21 22:25:42.332 [main] Main - Validating rules :'E001 - Missing required field
[INFO ] 2020-09-21 22:25:42.333 [main] Main -                   'E043 - Duplicated field
[INFO ] 2020-09-21 22:25:42.334 [main] Main -                   'W002 - Non standard field name
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.text.DecimalFormat.parse(DecimalFormat.java:2148)
	at java.base/java.text.NumberFormat.parseObject(NumberFormat.java:313)
	at org.apache.commons.validator.routines.AbstractFormatValidator.parse(AbstractFormatValidator.java:182)
	at org.apache.commons.validator.routines.AbstractNumberValidator.parse(AbstractNumberValidator.java:162)
	at org.apache.commons.validator.routines.FloatValidator.validate(FloatValidator.java:144)
	at org.mobilitydata.gtfsvalidator.parser.GtfsEntityParser.lambda$parse$1(GtfsEntityParser.java:177)
	at org.mobilitydata.gtfsvalidator.parser.GtfsEntityParser$$Lambda$162/0x0000000800de1568.accept(Unknown Source)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1087)
	at org.mobilitydata.gtfsvalidator.parser.GtfsEntityParser.parse(GtfsEntityParser.java:166)
	at org.mobilitydata.gtfsvalidator.usecase.ParseSingleRowForFile.execute(ParseSingleRowForFile.java:78)
	at org.mobilitydata.gtfsvalidator.Main.lambda$main$0(Main.java:102)
	at org.mobilitydata.gtfsvalidator.Main$$Lambda$143/0x0000000800dd12b0.accept(Unknown Source)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.mobilitydata.gtfsvalidator.Main.main(Main.java:94)

```

**Comment by fabrice-v** [comment]
Hi, thks for reporting.

We can't help but notice the use of a forwarded URL (transitfeeds domain), does that mean the validator could successfully download and unzip the feed from that URL?

Then, for the issue itself.
We are aware of memory issues with the validator related to the size of the input feeds. That it would happen with the MBTA feeds surprises us as we weren't able to reproduce the issue either locally or on our CI system.

To continue further we would need more information about the setup used so we could reproduce the issue on our side. Could you also verify this is an issue with the setup by running the same command outside the Docker environment on the same machine?

**Comment by e-lo** [comment]
> We can't help but notice the use of a forwarded URL (transitfeeds domain), does that mean the validator could successfully download and unzip the feed from that URL?

Strangely, yes. The MBTA feed doesn't have the same issue as reported for BART, etc. with the URLs.

> We are aware of memory issues with the validator related to the size of the input feeds. That it would happen with the MBTA feeds surprises us as we weren't able to reproduce the issue either locally or on our CI system

What is the general memory footprint? Might be good to post somewhere.

> Could you also verify this is an issue with the setup by running the same command outside the Docker environment on the same machine?

I was trying to use a reproducible environment by using Docker.  Suggest flipping this and adding a Dockerfile that works to the repo so that you don't have to troubleshoot everyone's individual hardware setup in the future.

**Comment by fabrice-v** [comment]
> Strangely, yes. The MBTA feed doesn't have the same issue as reported for BART, etc. with the URLs.

Thks for the information, that is strange indeed and we'll have to figure it out

> What is the general memory footprint? Might be good to post somewhere.

We are presently in the process of profiling as we haven't optimized for memory nor speed so far.

> I was trying to use a reproducible environment by using Docker.
Super good idea. Maybe the memory limits on such configuration are lower? Are you using a setup similar to what GitHub employs to run the validator on the MBTS feed?
