### ISSUE TITLE
[BUG] "this.originalRouteTypeInteger" is null in v1.3.0 SNAPSHOT

### ISSUE THREAD

**Issue by mcplanner** [MobilityData/gtfs-validator#399]
**Describe the bug**
The validator was unable to process a feed and gave an error.

**To Reproduce**
Run the validator on the following dataset: http://www.mst.org/google/google_transit.zip

**Expected behavior**
No notice should be generated in this case.

**Witnessed behavior**
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "this.originalRouteTypeInteger" is null
	at org.mobilitydata.gtfsvalidator.domain.entity.gtfs.routes.Route$RouteBuilder.build(Route.java:291)
	at org.mobilitydata.gtfsvalidator.usecase.ProcessParsedRoute.execute(ProcessParsedRoute.java:80)
	at org.mobilitydata.gtfsvalidator.Main.lambda$main$0(Main.java:114)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.mobilitydata.gtfsvalidator.Main.main(Main.java:94)
```

**Environment used**
- OS: macOS Catalina 10.15.6
- Java version: 11.0.5
- gtfs-validator version: gtfs-validator-v1.3.0-SNAPSHOT.jar

**Comment by fabrice-v** [comment]
Note that the provided dataset has been added to the automatic end to end checks for future code contributions, thank you again for reporting the issue and providing the dataset.
https://github.com/MobilityData/gtfs-validator/runs/1276757003?check_suite_focus=true

**Comment by fabrice-v** [comment]
Note that starting from today we provide an artifact containing the json reports for all gtfs datasets ran in the end to end GitHub Action workflow. 
![image](https://user-images.githubusercontent.com/55884852/96645891-45139500-12f9-11eb-96c7-aa31b4eaeb0d.png)

It's automatically created for each run. The first run providing it is visible here
https://github.com/MobilityData/gtfs-validator/actions/runs/318541798
