### ISSUE TITLE
[BUG] Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by mcplanner** [MobilityData/gtfs-validator#460]
**Describe the bug**
I encountered an error related to pointer exceptions when running the validator on Metrolink's feed.

**To Reproduce**
[Metrolink's](https://metrolinktrains.com/globalassets/about/gtfs/gtfs.zip) feed triggered this event.

**Expected behavior**
I did not expect this exception to occur.

**Witnessed behavior**
```
Exception in thread "main" java.lang.NullPointerException
	at java.base/java.util.Collections$UnmodifiableMap.<init>(Collections.java:1462)
	at java.base/java.util.Collections$UnmodifiableSortedMap.<init>(Collections.java:1820)
	at java.base/java.util.Collections.unmodifiableSortedMap(Collections.java:1805)
	at org.mobilitydata.gtfsvalidator.db.InMemoryGtfsDataRepository.getShapeById(InMemoryGtfsDataRepository.java:835)
	at org.mobilitydata.gtfsvalidator.usecase.usecasevalidator.StopTimeValidator.lambda$execute$0(StopTimeValidator.java:83)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.mobilitydata.gtfsvalidator.usecase.usecasevalidator.StopTimeValidator.lambda$execute$1(StopTimeValidator.java:81)
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:1067)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1087)
	at org.mobilitydata.gtfsvalidator.usecase.usecasevalidator.StopTimeValidator.execute(StopTimeValidator.java:76)
	at org.mobilitydata.gtfsvalidator.Main.main(Main.java:201)
```

**Environment used**
- OS: MacOS Catalina 10.15.6
- Java version: 15
- gtfs-validator version: 1.2.2

**Comment by fabrice-v** [comment]
Hi, thank you for reporting

would it be possible for a PR to be created following the instructions visible here: 
 - https://github.com/MobilityData/gtfs-validator/tree/v1.3.0#via-github-actions---run-the-validator-on-any-gtfs-archive-available-on-a-public-url 
- https://github.com/MobilityData/gtfs-validator/tree/v1.3.0#contribute
?

We will soon switch to community support only for local run of the validator.

**Comment by fabrice-v** [comment]
I should add, we designed those instructions so it's quick and easy to run the validator directly on GitHub and we get all the relevant information automatically, no report or call stack to copy and paste :)

**Comment by fabrice-v** [comment]
@Cristhian-HA will take if rom here with more details about our new Issues templates process! 👍

**Comment by Cristhian-HA** [comment]
Hello @mcplanner,

Thank you for contacting us. I would like to share with you that we have created different issue templates to facilitate the communication with our team and to provide better support to our members and the entire community. 

Would you please be so kind in opening a new one with the problem you are experiencing using the templates? we want to make sure we are capturing all the information needed to help you resolve your problem. 

If you have any questions or concerns please let me know, I will be happy to help.
