### ISSUE TITLE
NPE running on Netherlands GTFS during language validation

### ISSUE THREAD

**Issue by barbeau** [MobilityData/gtfs-validator#594]
**Summary**

When I run the current master branch as of https://github.com/MobilityData/gtfs-validator/commit/b9cd8020a7f514ce7b8ef77021fe4222091a700f on the GTFS Netherlands dataset:

http://gtfs.ovapi.nl/gtfs-nl.zip

...with:

`-i gtfs-openov-nl.zip -o output -t 8 -f nl-open`

...I get:

```
Cache for stop_times.txt departure_time: size = 77904, lookup count = 24365440, hits = 99.68%, misses = 0.32%
Cache for stop_times.txt stop_id: size = 43505, lookup count = 12182720, hits = 99.64%, misses = 0.36%
Cache for stop_times.txt stop_headsign: size = 1175, lookup count = 12182720, hits = 99.99%, misses = 0.01%
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.mobilitydata.gtfsvalidator.table.GtfsFeedLoader.lambda$loadAndValidate$3(GtfsFeedLoader.java:146)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
	at org.mobilitydata.gtfsvalidator.table.GtfsFeedLoader.loadAndValidate(GtfsFeedLoader.java:144)
	at org.mobilitydata.gtfsvalidator.cli.Main.main(Main.java:82)
Caused by: java.lang.NullPointerException
	at org.mobilitydata.gtfsvalidator.validator.MatchingFeedAndAgencyLangValidator.lambda$validate$0(MatchingFeedAndAgencyLangValidator.java:60)
Caused by: java.lang.NullPointerException

	at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
	at org.mobilitydata.gtfsvalidator.validator.MatchingFeedAndAgencyLangValidator.validate(MatchingFeedAndAgencyLangValidator.java:60)
	at org.mobilitydata.gtfsvalidator.table.GtfsFeedLoader.lambda$loadAndValidate$2(GtfsFeedLoader.java:139)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Validation took 44.547 seconds
agency.txt	29
attributions.txt	0
calendar.txt	0
calendar_dates.txt	64045
fare_attributes.txt	0
fare_rules.txt	0
feed_info.txt	1
frequencies.txt	0
levels.txt	0
pathways.txt	0
routes.txt	2561
shapes.txt	3947455
stop_times.txt	12182720
stops.txt	45087
transfers.txt	0
translations.txt	0
trips.txt	650548
```

**What I expect**

No NPE

**What I see**

NPE

**Steps to repro**

1. Run validator on Netherlands GTFS (http://gtfs.ovapi.nl/gtfs-nl.zip) with `-i gtfs-openov-nl.zip -o output -t 8 -f nl-open`

**Environment**

IntelliJ IDEA 2020.2.4 (Ultimate Edition)
Build #IU-202.8194.7, built on November 24, 2020
Runtime version: 11.0.9+11-b944.49 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1955M
Cores: 8
Non-Bundled Plugins: Lombook Plugin, idea.plugin.protoeditor, io.protostuff.protostuff-jetbrains-plugin, net.seesharpsoft.intellij.plugins.csv, org.jetbrains.kotlin

**Comment by barbeau** [comment]
I'm guessing that this is because the Netherlands GTFS doesn't include the optional `agency_lang` field in `agency.txt`
